// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPCuj1a8lxc8sH5k7XMJxHSNZp1rcClA',
    appId: '1:322401886878:web:d4b12b25030f192cccd18f',
    messagingSenderId: '322401886878',
    projectId: 'myapp-fe134',
    authDomain: 'myapp-fe134.firebaseapp.com',
    storageBucket: 'myapp-fe134.firebasestorage.app',
    measurementId: 'G-2641EC2CPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMZHbh1cSH8V15dNNeNEPD7lV4JB-1OsQ',
    appId: '1:322401886878:android:7b3b906812696cc0ccd18f',
    messagingSenderId: '322401886878',
    projectId: 'myapp-fe134',
    storageBucket: 'myapp-fe134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACtQ3999xhM0LmIurWhLaY4QN7yGJdmJk',
    appId: '1:322401886878:ios:a045bdf81ec49f65ccd18f',
    messagingSenderId: '322401886878',
    projectId: 'myapp-fe134',
    storageBucket: 'myapp-fe134.firebasestorage.app',
    iosClientId: '322401886878-c5hha53hhjh027k4pilooa0mgnq1t41q.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeExplorerPro',
  );
}
